### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by scratchyone** [jupiterio/Scratch-Messages#1]
The message count doesn't display correctly, and it doesn't show any messages.

**Comment by jupiterio** [comment]
Fixed now :)
Scratch had changed from 2 ul's (read and unread) to 1 inside a div.

**Comment by jupiterio** [comment]
Oh and oops. What do you mean by message count not displaying correctly? It's fine for me. Is it the color?

**Comment by scratchyone** [comment]
It's fine now. Thanks for fixing it. This is really helpful

On Sat, Apr 9, 2016 at 7:19 PM, jupiterio <notifications@github.com> wrote:

> Oh and oops. What do you mean by message count not displaying correctly?
> It's fine for me. Is it the color?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupiterio/Scratch-Messages/issues/1#issuecomment-207873942>
>



--
